### ISSUE TITLE
**PRIORITY**PFP does not update after change

### ISSUE THREAD

**Issue by markots** [TowneSquare/cred#138]
After a user changes their profile picture (PFP) and subsequently reloads the page, the displayed image does not reflect the recent change. Instead, the old image remains visible.
https://github.com/TowneSquare/cred/assets/112094900/dd008346-76a7-4884-921b-2f3d0b3e8f48

**Comment by markots** [comment]
> @markots Can you please share the video?

https://github.com/TowneSquare/cred/assets/112094900/7d870a3c-6396-4358-afe0-b27295536fcd

**Comment by codewizard870** [comment]
@Helme0315  can you check this issues on your side?
In this video that is marko shared, displaying changed image means profile image is already changed to new image in backend because FE displaying the changed image by using response from backend like this image.
![image](https://github.com/TowneSquare/cred/assets/91666375/eb4c8d7e-8408-4b40-a45d-fe9ed89b4342)

**Comment by codewizard870** [comment]
response.profile.avatar is not same as what I'm getting when I reload the page?

**Comment by markots** [comment]
done
